// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIOwbiPwIHF9gmRCCbTqpd6XYmsv_WBw',
    appId: '1:999291591820:web:YOUR_WEB_APP_ID',
    messagingSenderId: '999291591820',
    projectId: 'my-teacher-2c669',
    authDomain: 'my-teacher-2c669.firebaseapp.com',
    storageBucket: 'my-teacher-2c669.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIOwbiPwIHF9gmRCCbTqpd6XYmsv_WBw',
    appId: '1:999291591820:android:eb7793a40109f3566c2fa9',
    messagingSenderId: '999291591820',
    projectId: 'my-teacher-2c669',
    storageBucket: 'my-teacher-2c669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '999291591820',
    projectId: 'my-teacher-2c669',
    storageBucket: 'my-teacher-2c669.firebasestorage.app',
    iosBundleId: 'com.example.myTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '999291591820',
    projectId: 'my-teacher-2c669',
    storageBucket: 'my-teacher-2c669.firebasestorage.app',
    iosBundleId: 'com.example.myTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '999291591820',
    projectId: 'my-teacher-2c669',
    authDomain: 'my-teacher-2c669.firebaseapp.com',
    storageBucket: 'my-teacher-2c669.firebasestorage.app',
  );
}